default_language_version:
  python: python3

# Define common configuration variables
default_stages: [commit]

repos:
  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0 # Updated version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-case-conflict
      - id: check-added-large-files
      - id: check-merge-conflict # Added: catches merge conflict markers
      - id: check-json # Added: validate JSON files

  # Python code formatting
  - repo: https://github.com/psf/black
    rev: 23.9.1 # Updated version
    hooks:
      - id: black
        args: [--line-length, "299"]

  # Python import sorting
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  # Python upgrading syntax to newer version
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0 # Updated version
    hooks:
      - id: pyupgrade
        args: [--py38-plus]

  # Python docstring formatting
  - repo: https://github.com/myint/docformatter
    rev: v1.7.5 # Updated version
    hooks:
      - id: docformatter
        args:
          [
            --in-place,
            --wrap-summaries=99,
            --wrap-descriptions=99,
            --style=sphinx,
            --black,
          ]

  # Python docstring coverage checking
  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        args:
          [
            --verbose,
            --fail-under=100,
            --ignore-init-module,
            --ignore-init-method,
            --ignore-module,
            --ignore-nested-functions,
            -vv,
          ]
        exclude: "^tests/"

  # Replace flake8 with ruff (faster and more comprehensive)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.292
    hooks:
      - id: ruff
        args: ["--fix", "--line-length=299"]

  # Type checking with mypy (fixed)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        # Removed problematic types-all and added specific type stubs
        additional_dependencies:
          [types-requests, types-PyYAML, types-toml, types-setuptools]
        exclude: "^tests/"

  # Python security linter
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.5"
    hooks:
      - id: bandit
        args: ["-s", "B101"]

  # yaml formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3 # Updated version
    hooks:
      - id: prettier
        types: [yaml]
        exclude: "environment.yaml"

  # shell scripts linter
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6 # Updated version
    hooks:
      - id: shellcheck

  # md formatting
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17 # Updated version
    hooks:
      - id: mdformat
        args: ["--number"]
        additional_dependencies:
          - mdformat-gfm==0.3.7
          - mdformat-tables
          - mdformat_frontmatter

  # word spelling linter
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6 # Updated version
    hooks:
      - id: codespell
        args:
          - --skip=logs/**,data/**,*.ipynb,*.bib
          - --ignore-words-list=fro,ser,SER

  # jupyter notebook cell output clearing
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout

  # jupyter notebook linting
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0 # Updated version
    hooks:
      - id: nbqa-black
        args: ["--line-length=299"]
      - id: nbqa-isort
        args: ["--profile=black"]
      - id: nbqa-ruff # Changed from flake8 to ruff
        args: ["--line-length=299"]

  # Validate GitHub Actions workflows (new)
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.27.0
    hooks:
      - id: check-github-workflows
        files: ^\.github/workflows/

  # Check commit message format (new)
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.10.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
