# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - graphviz # Install the graphviz system package
  jobs:
    pre_build:
      # Pre-build step: Download auto_examples if needed
      - python scripts/download_auto_examples.py
    post_build:
      # Post-build cleanup if needed
      - echo "Documentation build completed"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf
  - epub

# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    - requirements: requirements.txt
    - requirements: requirements-dev.txt
    - method: pip
      path: .
