name: Update API Reference Documentation

on:
  push:
    branches: [main, master, dev]
    paths:
      - "kaira/**/*.py"
      - "scripts/generate_api_reference.py"
  pull_request:
    branches: [main, master, dev]
    paths:
      - "kaira/**/*.py"
      - "scripts/generate_api_reference.py"

# Cancel previous runs if a new push happens
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-api-reference:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Generate API reference documentation
        run: |
          python scripts/generate_api_reference.py docs/api_reference.rst

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet docs/api_reference.rst; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.changes.outputs.changed == 'true' && github.event_name == 'push'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/api_reference.rst
          git commit -m "Auto-update API reference documentation [skip ci]"
          git push

      - name: Comment on PR
        if: steps.changes.outputs.changed == 'true' && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🤖 **API Reference Updated**\n\nThe API reference documentation has been automatically updated based on the code changes in this PR.'
            })
