name: Lint

on:
  push:
    branches: [master, main, dev]
  pull_request:
    branches: [master, main]

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Check code formatting with Black
        run: |
          black --check kaira tests

      - name: Check import order with isort
        run: |
          isort --check-only --profile black kaira tests

      - name: Lint with flake8
        run: |
          flake8 kaira tests --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 kaira tests --count --max-complexity=10 --max-line-length=127 --statistics
