name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"  # Run at midnight every day

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v8
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.'
        stale-pr-message: 'This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.'
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        days-before-stale: 60
        days-before-close: 14
        exempt-issue-labels: 'bug,enhancement,documentation,good first issue'
        exempt-pr-labels: 'work in progress'
        exempt-all-milestones: true
        operations-per-run: 100